# Generated by Django 4.2.2 on 2023-09-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0005_alter_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=4096),
        ),
    ]
